### ISSUE TITLE
Not able to resolve the import static com.amazon.ask.quiz.util.QuestionUtils.getQuestionText;

### ISSUE THREAD

**Issue by borkya** [alexa/skill-sample-java-quiz-game#1]
Hi 
what is the maven dependency for this import?
I am not able to resolve this with any within the pom file.

**Comment by breedloj** [comment]
This static method lives within the quiz game module itself [here](https://github.com/alexa/skill-sample-java-quiz-game/blob/master/lambda/custom/src/main/java/com/amazon/ask/quiz/util/QuestionUtils.java#L48-L50). I am able to build the sample without issue. Can you paste the full error you're getting?

**Comment by franklin-lobb** [comment]
closing due to age
